# Generated by Django 6.0.4 on 2026-04-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownkey',
            name='sector',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
